### PR TITLE
fix: sync scroll bar when `columns` changed

### LINKED ISSUE #661: When horizontal scroll bar to disappear, the shadow display of the right fixed column is incorrect
When the column changes cause the horizontal scroll bar to disappear, the shadow of the fixed column on the right should disappear, but now it still shows.

- ref:  https://github.com/ant-design/ant-design/issues/31898

**Reproduce link:**
https://codesandbox.io/s/rc-table-issue-scroll-ping-right-sy0pq?file=/App.tsx

**Correct operation steps:**
1、Slide the horizontal scroll bar to the **right** side, the shadow of the fixed column on the **left** is displayed.
2、Click on the top `Scroll` checkbox, uncheck it.
3、You can observe that the shadow of the fixed column on the left **has disappeared** now.

https://user-images.githubusercontent.com/29560987/131251303-7f8b6b19-edcd-4338-b2bb-82044dd5deb9.mp4

**Incorrect operation steps:**
1、Slide the horizontal scroll bar to the **left** side, the shadow of the fixed column on the **right** is displayed.
2、Click on the top `Scroll` checkbox, uncheck it.
3、You can observe that the shadow of the fixed column on the right is **not disappeared**.

https://user-images.githubusercontent.com/29560987/131251306-9c66673d-2bfc-432d-975e-2cd08dba91db.mp4

### PR DESCRIPTION
**Pull request by adaex**
close #661

### CODE REVIEW

File: src/Table.tsx [hunk 1]
```diff
@@ -492,13 +492,13 @@ function Table<RecordType extends DefaultRecordType>(props: TableProps<RecordTyp
...
 
-  // Sync scroll bar when init or `horizonScroll` & `data` changed
+  // Sync scroll bar when init or `horizonScroll`, `data` and `columns` changed
   React.useEffect(() => triggerOnScroll, []);
   React.useEffect(() => {
     if (horizonScroll) {
       triggerOnScroll();
     }
-  }, [horizonScroll, data]);
+  }, [horizonScroll, data, columns]);
```
Comment (afc163) [inline src/Table.tsx:501]:
```suggestion
  }, [horizonScroll, data, columns.length]);
```

Comment (adaex) [reply src/Table.tsx]: done
